[[redirects]]
  from = "/priestley-chart/*"
  to = "https://fastidious-madeleine-82031e.netlify.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/trade-networks/*"
  to = "https://shiny-cannoli-08d363.netlify.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/battery-arbitrage/*"
  to = "https://peppy-pithivier-7e36d3.netlify.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}